version: "3"
services:
  nats:
    image: nats
    container_name: nats
    ports:
      - 4222:4222
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  
  rabbit:
    image: rabbitmq
    container_name: rabbit
    ports:
      - 15672:15672
      - 5672:5672
